// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (ia *IPAddressQuery) CollectFields(ctx context.Context, satisfies ...string) *IPAddressQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		ia = ia.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return ia
}

func (ia *IPAddressQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *IPAddressQuery {
	return ia
}
