// Code generated by entc, DO NOT EDIT.

package ent

import (
	"challenge/ent/ipaddress"
	"challenge/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IPAddressQuery is the builder for querying IPAddress entities.
type IPAddressQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.IPAddress
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IPAddressQuery builder.
func (iaq *IPAddressQuery) Where(ps ...predicate.IPAddress) *IPAddressQuery {
	iaq.predicates = append(iaq.predicates, ps...)
	return iaq
}

// Limit adds a limit step to the query.
func (iaq *IPAddressQuery) Limit(limit int) *IPAddressQuery {
	iaq.limit = &limit
	return iaq
}

// Offset adds an offset step to the query.
func (iaq *IPAddressQuery) Offset(offset int) *IPAddressQuery {
	iaq.offset = &offset
	return iaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iaq *IPAddressQuery) Unique(unique bool) *IPAddressQuery {
	iaq.unique = &unique
	return iaq
}

// Order adds an order step to the query.
func (iaq *IPAddressQuery) Order(o ...OrderFunc) *IPAddressQuery {
	iaq.order = append(iaq.order, o...)
	return iaq
}

// First returns the first IPAddress entity from the query.
// Returns a *NotFoundError when no IPAddress was found.
func (iaq *IPAddressQuery) First(ctx context.Context) (*IPAddress, error) {
	nodes, err := iaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ipaddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iaq *IPAddressQuery) FirstX(ctx context.Context) *IPAddress {
	node, err := iaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IPAddress ID from the query.
// Returns a *NotFoundError when no IPAddress ID was found.
func (iaq *IPAddressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ipaddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iaq *IPAddressQuery) FirstIDX(ctx context.Context) int {
	id, err := iaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IPAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IPAddress entity is found.
// Returns a *NotFoundError when no IPAddress entities are found.
func (iaq *IPAddressQuery) Only(ctx context.Context) (*IPAddress, error) {
	nodes, err := iaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ipaddress.Label}
	default:
		return nil, &NotSingularError{ipaddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iaq *IPAddressQuery) OnlyX(ctx context.Context) *IPAddress {
	node, err := iaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IPAddress ID in the query.
// Returns a *NotSingularError when more than one IPAddress ID is found.
// Returns a *NotFoundError when no entities are found.
func (iaq *IPAddressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = &NotSingularError{ipaddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iaq *IPAddressQuery) OnlyIDX(ctx context.Context) int {
	id, err := iaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IPAddresses.
func (iaq *IPAddressQuery) All(ctx context.Context) ([]*IPAddress, error) {
	if err := iaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return iaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (iaq *IPAddressQuery) AllX(ctx context.Context) []*IPAddress {
	nodes, err := iaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IPAddress IDs.
func (iaq *IPAddressQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := iaq.Select(ipaddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iaq *IPAddressQuery) IDsX(ctx context.Context) []int {
	ids, err := iaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iaq *IPAddressQuery) Count(ctx context.Context) (int, error) {
	if err := iaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return iaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (iaq *IPAddressQuery) CountX(ctx context.Context) int {
	count, err := iaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iaq *IPAddressQuery) Exist(ctx context.Context) (bool, error) {
	if err := iaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return iaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (iaq *IPAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := iaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IPAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iaq *IPAddressQuery) Clone() *IPAddressQuery {
	if iaq == nil {
		return nil
	}
	return &IPAddressQuery{
		config:     iaq.config,
		limit:      iaq.limit,
		offset:     iaq.offset,
		order:      append([]OrderFunc{}, iaq.order...),
		predicates: append([]predicate.IPAddress{}, iaq.predicates...),
		// clone intermediate query.
		sql:    iaq.sql.Clone(),
		path:   iaq.path,
		unique: iaq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IPAddress.Query().
//		GroupBy(ipaddress.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (iaq *IPAddressQuery) GroupBy(field string, fields ...string) *IPAddressGroupBy {
	group := &IPAddressGroupBy{config: iaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := iaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return iaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//	}
//
//	client.IPAddress.Query().
//		Select(ipaddress.FieldUUID).
//		Scan(ctx, &v)
//
func (iaq *IPAddressQuery) Select(fields ...string) *IPAddressSelect {
	iaq.fields = append(iaq.fields, fields...)
	return &IPAddressSelect{IPAddressQuery: iaq}
}

func (iaq *IPAddressQuery) prepareQuery(ctx context.Context) error {
	for _, f := range iaq.fields {
		if !ipaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iaq.path != nil {
		prev, err := iaq.path(ctx)
		if err != nil {
			return err
		}
		iaq.sql = prev
	}
	return nil
}

func (iaq *IPAddressQuery) sqlAll(ctx context.Context) ([]*IPAddress, error) {
	var (
		nodes = []*IPAddress{}
		_spec = iaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &IPAddress{config: iaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, iaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (iaq *IPAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iaq.querySpec()
	_spec.Node.Columns = iaq.fields
	if len(iaq.fields) > 0 {
		_spec.Unique = iaq.unique != nil && *iaq.unique
	}
	return sqlgraph.CountNodes(ctx, iaq.driver, _spec)
}

func (iaq *IPAddressQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := iaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (iaq *IPAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ipaddress.Table,
			Columns: ipaddress.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ipaddress.FieldID,
			},
		},
		From:   iaq.sql,
		Unique: true,
	}
	if unique := iaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := iaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipaddress.FieldID)
		for i := range fields {
			if fields[i] != ipaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iaq *IPAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iaq.driver.Dialect())
	t1 := builder.Table(ipaddress.Table)
	columns := iaq.fields
	if len(columns) == 0 {
		columns = ipaddress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iaq.sql != nil {
		selector = iaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iaq.unique != nil && *iaq.unique {
		selector.Distinct()
	}
	for _, p := range iaq.predicates {
		p(selector)
	}
	for _, p := range iaq.order {
		p(selector)
	}
	if offset := iaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IPAddressGroupBy is the group-by builder for IPAddress entities.
type IPAddressGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iagb *IPAddressGroupBy) Aggregate(fns ...AggregateFunc) *IPAddressGroupBy {
	iagb.fns = append(iagb.fns, fns...)
	return iagb
}

// Scan applies the group-by query and scans the result into the given value.
func (iagb *IPAddressGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := iagb.path(ctx)
	if err != nil {
		return err
	}
	iagb.sql = query
	return iagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (iagb *IPAddressGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := iagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(iagb.fields) > 1 {
		return nil, errors.New("ent: IPAddressGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := iagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (iagb *IPAddressGroupBy) StringsX(ctx context.Context) []string {
	v, err := iagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = iagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (iagb *IPAddressGroupBy) StringX(ctx context.Context) string {
	v, err := iagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(iagb.fields) > 1 {
		return nil, errors.New("ent: IPAddressGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := iagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (iagb *IPAddressGroupBy) IntsX(ctx context.Context) []int {
	v, err := iagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = iagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (iagb *IPAddressGroupBy) IntX(ctx context.Context) int {
	v, err := iagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(iagb.fields) > 1 {
		return nil, errors.New("ent: IPAddressGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := iagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (iagb *IPAddressGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := iagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = iagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (iagb *IPAddressGroupBy) Float64X(ctx context.Context) float64 {
	v, err := iagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(iagb.fields) > 1 {
		return nil, errors.New("ent: IPAddressGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := iagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (iagb *IPAddressGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := iagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (iagb *IPAddressGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = iagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (iagb *IPAddressGroupBy) BoolX(ctx context.Context) bool {
	v, err := iagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (iagb *IPAddressGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range iagb.fields {
		if !ipaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := iagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (iagb *IPAddressGroupBy) sqlQuery() *sql.Selector {
	selector := iagb.sql.Select()
	aggregation := make([]string, 0, len(iagb.fns))
	for _, fn := range iagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(iagb.fields)+len(iagb.fns))
		for _, f := range iagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(iagb.fields...)...)
}

// IPAddressSelect is the builder for selecting fields of IPAddress entities.
type IPAddressSelect struct {
	*IPAddressQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ias *IPAddressSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ias.prepareQuery(ctx); err != nil {
		return err
	}
	ias.sql = ias.IPAddressQuery.sqlQuery(ctx)
	return ias.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ias *IPAddressSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ias.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ias.fields) > 1 {
		return nil, errors.New("ent: IPAddressSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ias.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ias *IPAddressSelect) StringsX(ctx context.Context) []string {
	v, err := ias.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ias.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ias *IPAddressSelect) StringX(ctx context.Context) string {
	v, err := ias.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ias.fields) > 1 {
		return nil, errors.New("ent: IPAddressSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ias.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ias *IPAddressSelect) IntsX(ctx context.Context) []int {
	v, err := ias.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ias.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ias *IPAddressSelect) IntX(ctx context.Context) int {
	v, err := ias.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ias.fields) > 1 {
		return nil, errors.New("ent: IPAddressSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ias.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ias *IPAddressSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ias.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ias.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ias *IPAddressSelect) Float64X(ctx context.Context) float64 {
	v, err := ias.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ias.fields) > 1 {
		return nil, errors.New("ent: IPAddressSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ias.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ias *IPAddressSelect) BoolsX(ctx context.Context) []bool {
	v, err := ias.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ias *IPAddressSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ias.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{ipaddress.Label}
	default:
		err = fmt.Errorf("ent: IPAddressSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ias *IPAddressSelect) BoolX(ctx context.Context) bool {
	v, err := ias.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ias *IPAddressSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ias.sql.Query()
	if err := ias.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
